### ISSUE TITLE
incorrect response when using: response.text()

### ISSUE THREAD

**Issue by dearfrankg** [node-fetch/node-fetch#1060]
I'm getting an incorrect response when using:  response.text()

**Reproduction**

No easy way to reproduce since it requires credentials to access the server.  We can go there if absolutely necessary.

**Expected behavior**

CORRECT TEXT RESPONSE using postman

```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://InspectionService/">
    <SOAP-ENV:Body>
        <ns1:GetRequestResponse>
            <RequestResponseResult>
                <success>true</success>
                <status>closed</status>
                <state>7</state>
                <message>Inspection Request Complete</message>
                <report>https://oneguardinspections.com/components/com_rstickets/files/2020/12/22/PRCO18/PRCO-0000000018_PDF_Report.pdf</report>
            </RequestResponseResult>
        </ns1:GetRequestResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

INCORRECT TEXT RESPONSE  from response.text()

```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:ns1="http://InspectionService/">
    <SOAP-ENV:Body>
        <ns1:GetRequestResponse>
            <RequestResponseResult>
                <success>true</success>
                <status/>
                <state/>
                <message/>
                <report/>
            </RequestResponseResult>
        </ns1:GetRequestResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | v12.16.1
| npm              | 6.14.8
| Operating System |

**Additional context**

As you probably notice, the response text has a value for the success field but no other fields.

**Comment by jimmywarting** [comment]
My bet is that there is nothing wrong with node-fetch's way of returning the `response.text()` we have no knowledge about the response and we don't modify it in anyway.
You are already getting something like a xml response so it have to be the server that gives you the wrong response. possible due to wrongly sent data. 

I'm getting an incorrect response when using: response.text()

Reproduction

> Steps to reproduce the behavior:
> No easy way to reproduce since it requires credentials to access the server. We can go there if absolutely necessary.

At least some code would be helpful to try and figure out what is being sent and how it's being sent/constructed.
The things you don't want to share can be obfusicated with having just variable names or just dummy data...

A comparison of postman vs fetch request headers, body & method is useful so we can figure out what the differences is.
