### ISSUE TITLE
Issue when using on ubuntu server

### ISSUE THREAD

**Issue by jonkootje** [node-fetch/node-fetch#1062]
I'm trying to use node-fetch to send requests to https://www.zalando.nl/ . It works fine when I run my script on my laptop, but when I move it to an ubuntu server the request does not resolve. It only happends when I send it to this domain, other domains just work fine.

Does anyone know what is going on and how I can debug this issue?

**Comment by tekwiz** [comment]
@jonkootje Please start by following the issue template.  We need at least a code snippet, version numbers for node-fetch, node, npm, and the OS, and an error message and stack trace (if applicable).  Also, please be sure to notate where your code hangs or where the error is thrown.  Finally, since I've been working on similar problems, please run your script with the following and provide the output (just be sure to sanitize any sensitive data):
```
NODE_DEBUG=http,https,net,stream
```

**Comment by jonkootje** [comment]
I found the issue. The host had blocked the IP address of the server I was using. They try to do that with all major hosting providers apparently. Just strange that node-fetch is not giving me any errors about it.
