### ISSUE TITLE
3.0.0 beta.10: TypeError: Cannot read property 'body' of null

### ISSUE THREAD

**Issue by weijarz** [node-fetch/node-fetch#1220]
```js
import fetch from 'node-fetch'

const response = await fetch('https://blog.logrocket.com/feed')
const body = await response.text()

console.log(body)
```

throws
```
file:///root/fetchbug/node_modules/node-fetch/src/index.js:99
			response.body.destroy(error);
			         ^

TypeError: Cannot read property 'body' of null
    at file:///root/fetchbug/node_modules/node-fetch/src/index.js:99:13
    at TLSSocket.<anonymous> (file:///root/fetchbug/node_modules/node-fetch/src/index.js:310:6)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7)
```

| software         | version
| ---------------- | -------
| node-fetch       | 3.0.0-beta.10
| node             | v14.16.0
| npm              | 7.17.0
| Operating System | archlinux

**Comment by jimmywarting** [comment]
Able to reproduce
works in v2...

**Comment by jimmywarting** [comment]
@octet-stream would you like to take a stab at #1220 #1219 before we ship v3? 
I'm on vacation ATM. #1064 broke some stuff between beta.9 and beta.10

**Comment by octet-stream** [comment]
Will see what I can do.

**Comment by octet-stream** [comment]
It seems like the response is `null` when `fixResponseChunkedTransferBadEnding` is called if the request has been redirected. There's no check for `response` being null here:
https://github.com/node-fetch/node-fetch/blob/b50fbc105755123cad34fb0bc9d5653ecc693b8a/src/index.js#L98-L100

Adding this check fixes this issue. But I'm not sure yet if this is the right solution. ~~And I'm not one of node-fetch members so don't expect match from me because I'm unfamiliar with the codebase :D~~ However I will figure this out.

**Comment by tekwiz** [comment]
@jimmywarting I'll take a look at this today.

**Comment by tekwiz** [comment]
@jimmywarting See #1222 for fix
