### ISSUE TITLE
require node-fetch is throw error “ syntax error ”

### ISSUE THREAD

**Issue by Hooho** [node-fetch/node-fetch#1230]

**Comment by Hooho** [comment]
![image](https://user-images.githubusercontent.com/18716647/127659062-fcb54b2a-cbcd-472f-91bf-8684cda03911.png)

**Comment by jimmywarting** [comment]
I suspect you are trying out `node-fetch@v3.0.0-beta.10` we converted our package to use only ESM syntax
we no longer support cjs and switched to using import/export instead

> I know import is not supported in node，so it is a syntax error，but why not-fetch will use it?

I guess you are wrong. imports have been supported in nodejs ever since v12.20 (with top level await in v14 or something like that)
So here is what you have to do:

1. Update and use a newer nodejs version that is 12.20 or higher
2. Change package.json to include a `"type": "module"`
3. use `import fetch from 'node-fetch'`
  or alternative use `import('node-fetch')` if you are stuck with using cjs

**Comment by jimmywarting** [comment]
Locking b/c it's nicer to keep the discussion in one place.
(We still keep a open mind and looking for a solution - it dose not mean we will overlook this Issue)

Feel free to keep the discussion in #1227 where most of the discussion is already happening
