### ISSUE TITLE
IPv6 literals are broken

### ISSUE THREAD

**Issue by serverwentdown** [node-fetch/node-fetch#1267]
**Reproduction**

```
import fetch from 'node-fetch';
fetch('http://[::1]:8080')
  .then(res => console.debug('ok'))
  .catch(err => console.error('err', err));
```

```
getaddrinfo ENOTFOUND [::1]
```

**Expected behavior**

- If there is a server at `[::1]:8080`, it should not fail

**Cause**

- This was working fine in 2.x, but in 3.x the URL parser switched from Node's `url.Url` to WHATWG's `URL`

```
> u = url.parse('http://[::1]');
Url {
...
  host: '[::1]',
  hostname: '::1',
...
}
> u = new URL('http://[::1]')
URL {
...
  host: '[::1]',
  hostname: '[::1]',
...
}
```

- [offending line, 3.x](https://github.com/node-fetch/node-fetch/blob/914ce6be5ec67a8bab63d68510aabf07cb818b6d/src/request.js#L265) 
- [2.x](https://github.com/node-fetch/node-fetch/blob/b5e2e41b2b50bf2997720d6125accaf0dd68c0ab/src/request.js#L245) passes `url.Url` directly to `request()`

**Comment by jimmywarting** [comment]
Hmm, doing `new URL('http://[::1]').hostname === '[::1]'` feels more correct.
and using URL instead of url.parse is more fetch-spec'ed ish

But i guess historically `http.request` was first built with the legacy `url.parse` in mind
maybe we could use the whatwg URL parser trough out the hole system but just right before we call get a node http request option: https://github.com/node-fetch/node-fetch/blob/2603c67f1840fb4a43e0837099a3b2725e8f615e/src/request.js#L208-L210

then maybe we can convert it back to the historical format?

url.parse(new URL('http://[::1]').toString())

Also wondering if we _really_ need all dose spreaded out, thinking maybe we could just do `http.request(full_url_string, { headers, ...rest })`

**Comment by serverwentdown** [comment]
I propose fixing this with:

```
let hostname = parsedURL.hostname;
if (hostname.startsWith("[") && hostname.endsWith("]")) {
  hostname = hostname.substring(1, hostname.length - 1)
}

// ...

const requestOptions = {
  // ...
  hostname: hostname,

```
