### ISSUE TITLE
fetch doesn't allow for AbortSignal custom impl with constructor name other then exactly AbortSignal

### ISSUE THREAD

**Issue by Veetaha** [node-fetch/node-fetch#751]
May I ask you to elaborate on the purpose of this validation?

https://github.com/node-fetch/node-fetch/blob/7c66f9ce822a3a06fe01eb583a30b4c087c596c2/src/utils/is.js#L53-L58

For my use case, it is redundant. I want to pass a custom adapter from `vscode.CancellationToken` to `AbortSignal`:
```ts
import { AbortSignal } from "node_fetch/externals";

class CancellationSignal implements AbortSignal {
    subscriptions = new WeakMap<Listener, vscode.Disposable>();

    constructor(private readonly ct: vscode.CancellationToken) {}

    get aborted() {
        return this.ct.isCancellationRequested;
    }

    addEventListener(_type: "abort", listener: Listener, _opts?: unknown) {
        this.subscriptions.set(listener, this.ct.onCancellationRequested(listener, this));
    }

    removeEventListener(_type: "abort", listener: Listener) {
        this.subscriptions.get(listener)?.dispose();
    }

    // Some excess APIs that are not used by `node_fetch` impl
    onabort = null
    dispatchEvent() { return false; }
}
```
This is very annoying that I cannot name my class how I want. Besides that why can't I pass a simple object literal that conforms to `AbortSignal`? There is no such explicit contract that an instance of abort signal passed to fetch must be a custom class instance, since `AbortSignlas` is nothing but an interface...

**Comment by dzek69** [comment]
I agree. This is also very annoying when you bundle and minify your code. Minifiers will change the name of your class and node-fetch will fail on that.

If somebody finds that useful - that's fine. But having some global configuration to disable this behavior would be nice.

**Comment by jimmywarting** [comment]
Bundlers may minify classes and minify names but if you add `Symbol.toStringTag` to your class that's equal to `AbortSignal` then you may be fine with minimizing it.

Also i don't think speced polyfilled api's should mangle the class names to something short.

**Comment by ww-k** [comment]
> Bundlers may minify classes and minify names but if you add [Symbol.toStringTag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) to your class that's equal to `AbortSignal` then you will be fine with minimizing it and using a own custom abort signal. That's how we check if it's an AbortSignal
> 
> Also i don't think speced polyfilled api's should mangle the class names to something short.

I'm sorry. `abort-controller` package which used by  [the example](https://github.com/node-fetch/node-fetch#request-cancellation-with-abortsignal) in here , not implement (Symbol.toStringTag)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag], and not work after Bundlers minified.

I think, check constructor name is not good way.

**Comment by Veetaha** [comment]
Ah, sorry for not responding, I've the new message pinned me.
So to my mind checking the output of `toStringTag()` is very unintuitive and uncommon. It doesn't check that the object structurally conforms to `AbortSignal` interface.
Also suppose every JS library in the world checked their inputs to conform to interfaces via `toStringTag()`, then you wouldn't be able to create an object that implements multiple interfaces, because it can return only one string in `.toStringTag()` with one interface name.

Other than that you'd never expect that just doing refactoring and renaming your classes will break your program (especially disappointing when this fails in production). I've never seen user class name's being the item of semver compatibility which is kinda one of the most volatile things in end code.

What the proper solution here would be then? I really don't see anything good because JS doesn't have language-builtin support for type checking interfaces so we may just skip this check at all, because even right now it doesn't bring us significant advantages (as I described higher). I'd just suppose that people are not trying to shoot themselves in the leg and pass anything but `AbortSignal`-conformant object, which is 99% true especially due to the rise of popularity of TypeScript

**Comment by jimmywarting** [comment]
@ww-k Again we don't check constructor name, we are currently checking the the `Symbol.toStringTag`
And it's easy to implement and works with mangled class names also 
```js
class F { // <--- minified name
  get [Symbol.toStringTag]() {
    return 'AbortSignal'
  }
}

function isAbortSignal(object) {
  return (
    typeof object === 'object' &&
    object[Symbol.toStringTag] === 'AbortSignal'
  )
}

isAbortSignal(new F()) // true
new F().constructor.name // F
new F().toString() // "[object AbortSignal]"
```

And `abort-controller` dose also [add it](https://github.com/mysticatea/abort-controller/blob/a935d38e09eb95d6b633a8c42fcceec9969e7b05/src/abort-signal.ts#L81-L87)

**Comment by jimmywarting** [comment]
Linking this issue: #667 #673

**Comment by Veetaha** [comment]
> Again we don't check constructor name, we are currently checking the the

Hmm, I might've been wrong about class names (I wonder why I thought they matter here in the first place).

@jimmywarting could you elaborate on the purpose of this check, anyway?  `object[Symbol.toStringTag] === 'AbortSignal'`

It won't detect that the user passes a truly valid object that implements abort signal's signature. E.g. you in your example just created such an object that even has `'AbortSignal'` in string tag, but doesn't implement the required methods.

> posted by @jimmywarting 
> ```ts
> class F { // <--- minified name
>  get [Symbol.toStringTag]() {
>    return 'AbortSignal'
>  }
> }
> ```

Besides that, I've never implemented `toStringTag` manually, and seeing it in regular code is surprising. Could you give more examples of libraries where `toStringTag` is used for the good outside of `node_fetch`.

Also, it is not specified anywhere (including [the dom specs](https://dom.spec.whatwg.org/#interface-AbortSignal)) that `AbortSignal`  is **required** to have this invariant.


If my comment wasn't persuasive enough, then we should at the very least document this quirk, so that users like me don't stumble upon this behavior without being prepared.

**Comment by jimmywarting** [comment]
> The Symbol.toStringTag well-known symbol is a string valued property that is used in the creation of the default string description of an object. It is accessed internally by the Object.prototype.toString() method.
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag

---

it [exist on all DOM object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag#toStringTag_available_on_all_DOM_prototype_objects) even those things that where invented long before Symbol arrived to JS. including `AbortSymbol[Symbol.toStringTag]`
Since all object inherit this automatically (due to this change https://github.com/heycam/webidl/pull/357) it will make it so new spec don't have to mention implementing the `Symbol.toStringTag`

---

I know many libraries that uses `Object.prototype.toString.call(value)` to determine the internal JavaScript [[Class]] of an object. many uses this hack to look if a value is equal to something
jQuery, lodash, angular, vue [this random SO question](https://stackoverflow.com/a/643827/1008999) they all use this kind of type checking also. 
some need to know the differences between Blob and File and they mostly have the same methods. 

---

Now the problem of supporting polyfilled things with this type checking with a custom class is that the default toString tag defaults to `[object Object]`
```js
// custom Blob polyfill for browser that don't have it
class Blob {...}
Object.prototype.toString.call(new Blob()); // "[object Object]"
```
this can be resolved by using symbol.toStringTag so it becomes `"[object Blob]"`

it get even more problematic when it gets converted all the way back to es3-5 to be functions instead of a class and making the class names to one letter in minifier. that's why many polyfilled libraries now uses `Symbol.toStringTag` 
We also uses it for Request, Response and Headers to be spec compatible.

---

It is not so common to see this symbol being used by own self built classes and be used for type checking but they are very much common in polyfills so the determination of some WebIDL (DOM) object will pass.

---

Now we don't necessary have to do the type checking, most will probably send in a "correct-polyfilled" signal anyway, who would ever send in something like `fetch(..., {signal: not_a_abortsignal}`? very very few ppl would. but that is an other mather. I think it's good with at least one check to determinate if something is a signal or not but i don't think we have to check all all method to determinate if it conforms to being spec compatible. think that just adds lots of boiler code

**Comment by ww-k** [comment]
> @ww-k, @Veetaha Again we don't check constructor name, we are currently checking the the `Symbol.toStringTag`
> And it's easy to implement and works with mangled class names also
> 
> ```js
> class F { // <--- minified name
>   get [Symbol.toStringTag]() {
>     return 'AbortSignal'
>   }
> }
> 
> function isAbortSignal(object) {
>   return (
>     typeof object === 'object' &&
>     object[Symbol.toStringTag] === 'AbortSignal'
>   )
> }
> 
> isAbortSignal(new F()) // true
> new F().constructor.name // F
> new F().toString() // "[object AbortSignal]"
> ```
> 
> And `abort-controller` dose also [add it](https://github.com/mysticatea/abort-controller/blob/a935d38e09eb95d6b633a8c42fcceec9969e7b05/src/abort-signal.ts#L81-L87)
Yes, I see. 
Is node-feth will release an 2.6.x to update `isAbortSignal` to new method in 3.x ?

**Comment by jimmywarting** [comment]
Closing... 
- Mangling class name is fine. 
- Using a AbortSignal that lacks a missing `symbol.toStringTag` is not...

Also I took a extra peek on our `isAbortSignal` function and we also check if the name match `EventTarget`... this is weird. should remove that (but maybe not right now as it might break something, on v4 we will drop older node support when v12 goes EOL and we can start using built in AbortController provided by NodeJS.
