### ISSUE TITLE
`AbortError` is not exported

### ISSUE THREAD

**Issue by OliverJAsh** [node-fetch/node-fetch#792]
Hi, I noticed that `FetchError` is exported but `AbortError` is not. This means I'm unable to use the error type. Is this intentional?

(Apologies if this is already fixed in the v3 beta.)

**Comment by Richienb** [comment]
I wouldn't think so since aborts should be detectable.

**Comment by pkruk2** [comment]
If I see correctly, this will be fixed in version 3.0.0

Do you have an ETA for that version ?

---

Background: I have a wrapper for fetch() which also calls json(). I suppose that it's possible that abort signal comes after fetch() and before/during json() call, and in such case the json() will not be aborted (AbortError will not be thrown), right?

Since json() call can also take some time for large responses, I think it'd be nice if it was cancellable. But since it's not, I though I could throw the AbortError myself from my node-fetch wrapper, as a workaround.

**Comment by jkhsjdhjs** [comment]
I just stumbled across this issue in `node fetch 2.6.1`, since this has only been fixed for the new `3.x` version. @Richienb would you mind backporting the fix to `2.x`?

**Comment by frederikprijck** [comment]
Stumbled upon this, opened a PR to backport your changes to v2 @Richienb.

Happy to patch the types on definetly typed as well if this get merged.
