### ISSUE TITLE
Feature request: what about robots.txt?

### ISSUE THREAD

**Issue by AndovaBegarin** [node-fetch/node-fetch#867]
(Please ignore/delete if I am misunderstanding what Node-Fetch is.)

I only found out about this by seom requests to a Website I mange. Heere is the log excerpt:

155.64.23.62 - - [24/May/2020:04:52:48 -0600] "HEAD [redacted] HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
155.64.23.62 - - [24/May/2020:04:52:48 -0600] "GET [redacted] HTTP/1.1" 200 29992 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
155.64.23.62 - - [24/May/2020:04:52:48 -0600] "GET [redacted] HTTP/1.1" 200 11812 "[redacted]" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

(And five more.)

No robots.txt check. Is that okay?
Note also subsequent requests changed the user-agent string. Is that okay?

**Comment by jimmywarting** [comment]
node-fetch is not a robot or a spider that scans websites or anything like that. node-fetch is a light-weight module that brings window.fetch to Node.js to help developers make requests similar to curl or wget. so it don't do any special handling with robots.txt. 

robots.txt should be handle by the developers that use node-fetch and respect it.

ps node-fetch don't automatically changes the user agent to be something dynamic. and it don't try to mimic any browser client. node-fetch defaults to using `"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"` but will soon be changed to just be `node-fetch` in later version, still doe developer have the option to change the user-agent if they want to do that.

**Comment by AndovaBegarin** [comment]
Okay. Thank you for that information. But someone is making many requests to some websites I manage, all using "node-fetch" and then using a different UA - same IP - so many requests it's suspicious. Why do you think that is? (Rhetorical.)

I just block that IP now.

Thanks. Let's close this.

**Comment by jimmywarting** [comment]
> Why do you think that is? (Rhetorical.)

Don't know... hardly know anything about your webpage and what it dose. I have made a couple of bots/scrapers sometimes myself in my days for personal use...

- Would try to google up the ip address to try and found out more of what it's.

- Would also try to investigate what kind of web pages dose it scan. is it trying to scrape something off your site? try searching for duplicate content on other sites... observe the behavior of the client and what he is doing.

- If you have a rest API, why isn't he using that instead?

- instead of maybe flat out block the ip. give him a message and maybe let him contact you somehow.

- also be aware of `x-forward-for` some agents can spoof it if you trust proxies.

- Also this will only become a cat and mouse game. if he really wants to make request to your page he will find a way to do so.

- You could look into using something like a annoying captcha wall or a rate limit of that sort also.

**Comment by jimmywarting** [comment]
dDOS could be one thing also 😉

**Comment by jimmywarting** [comment]
feels a bit special that he is doing a HEAD request first and gather some response headers before doing the other GET requests...

Normally not many developer are changing the user-agent if they don't have to. a CORS proxy could just simply forward all request headers.

**Comment by jimmywarting** [comment]
https://cleantalk.org/blacklists/as16733
