### ISSUE TITLE
Question: using client side certificate

### ISSUE THREAD

**Issue by bistvan** [node-fetch/node-fetch#904]
Is there any way to pass custom arguments to the request, such as:

`pfx: FileSystem.readFileSync('./certificate.pkcs12') ,`
`passphrase: 'pwd'`

Because eventually the `https.request({...})` would accept such parameters.

**Comment by tekwiz** [comment]
@bistvan Use an [`https.Agent`](https://nodejs.org/api/https.html#https_class_https_agent).  Options passed to its constructor will be passed on to [`tls.connect()`](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) (which also takes options for [`tls.createSecureContext()`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options)).

```js
const pfx = fs.readFileSync('cert.pkcs12');
const passphrase = 'thepassphrase';
const agent = https.Agent({ pfx, passphrase });
const res = await fetch(uri, { agent });
```

**Comment by silverwind** [comment]
> Options passed to its constructor will be passed on to tls.connect()

This does seem to be undocumented behaviour according to [`https.Agent` docs](https://nodejs.org/api/https.html#https_new_agent_options). The documented way is to pass client certificate options to [`https.request`](https://nodejs.org/api/https.html#https_https_request_options_callback), but node-fetch does not allow passing those in fetch's `options`.

**Comment by michaelrommel** [comment]
I have a related question: I am using the passing of an `https.Agent` to add a cert and key to the options object and that works well, because the `agent` is passed on when creating the actual Request object in line 102 https://github.com/node-fetch/node-fetch/blob/1780f5ae89107ded4f232f43219ab0e548b0647c/src/request.js#L102 

However, when I want to do the same thing with a httpsProxyAgent like https://github.com/TooTallNate/node-https-proxy-agent the cert and key would be used in the `tls.connect()` call to the proxy (if it even were an https proxy and not a http proxy) and are not passed through to the tls connection upgrade call to the destination server. The proxy Agent actually passes on the Request objects options, though, so if it would be possible to add cert and key as recognized additional options to the node-fetch constructor this would help.

I tried that by adding cert and key in `src/request.js` in the Request constructor and also at the end of `getNodeRequestOptions` and it would work. Would you consider adding this here (and should I make a PR) or would it make more sense to talk to the httpsProxyAgent author to add additional options there that will get passed onto the next connection layer once the http connection to the proxy is established?

**Comment by michaelrommel** [comment]
I made a fork and added the cert/key variables to the `getNodeRequestOptions(request)` function the same as with `agent`.

**Comment by t-net** [comment]
Why is this topic closed? How are we meant to pass TLS options like pfx and passphrase to https.request if the agent property is already using the proxy agent?
